import type { TCard, Transaction } from "../types";

export const DUMMY_CARDS: TCard[] = [
  {
    cardNumber: "1234567890123456",
    cardHolderName: "John Doe",
    expiryDate: "12/25",
    cardType: "credit",
    cvv: "123",
    bankName: "Chase Bank",
    availableBalance: 243254,
  },
  {
    cardNumber: "9876543210987654",
    cardHolderName: "Jane Smith",
    expiryDate: "11/24",
    cardType: "debit",
    cvv: "456",
    bankName: "Bank of America",
    availableBalance: 234,
  },
  {
    cardNumber: "5555666677778888",
    cardHolderName: "Alice Johnson",
    expiryDate: "10/23",
    cardType: "credit",
    cvv: "789",
    bankName: "Wells Fargo",
    availableBalance: 547640,
  },
];
export const DUMMY_CARD_DATA: TCard = {
  cardNumber: "1234567890123456",
  cardHolderName: "John Doe",
  expiryDate: "12/25",
  cardType: "credit",
  cvv: "123",
  bankName: "Chase Bank",
  availableBalance: 45744,
};

export const DUMMY_TRANSACTIONS: Transaction[] = [
  {
    id: "1",
    date: "2024-01-15",
    description: "Coffee Shop",
    amount: -4.5,
    category: "Food & Drink",
    type: "debit",
  },
  {
    id: "2",
    date: "2024-01-14",
    description: "Salary Deposit",
    amount: 3500,
    category: "Income",
    type: "credit",
  },
  {
    id: "3",
    date: "2024-01-13",
    description: "Gas Station",
    amount: -65.2,
    category: "Transportation",
    type: "debit",
  },
  {
    id: "4",
    date: "2024-01-12",
    description: "Grocery Store",
    amount: -127.85,
    category: "Groceries",
    type: "debit",
  },
  {
    id: "5",
    date: "2024-01-11",
    description: "Online Shopping",
    amount: -89.99,
    category: "Shopping",
    type: "debit",
  },
  {
    id: "6",
    date: "2024-01-10",
    description: "Restaurant",
    amount: -42.75,
    category: "Food & Drink",
    type: "debit",
  },
  {
    id: "7",
    date: "2024-01-09",
    description: "Electric Bill",
    amount: -156.34,
    category: "Utilities",
    type: "debit",
  },
  {
    id: "8",
    date: "2024-01-08",
    description: "ATM Withdrawal",
    amount: -100,
    category: "Cash",
    type: "debit",
  },
  {
    id: "9",
    date: "2024-01-07",
    description: "Freelance Payment",
    amount: 850,
    category: "Income",
    type: "credit",
  },
  {
    id: "10",
    date: "2024-01-06",
    description: "Pharmacy",
    amount: -23.67,
    category: "Healthcare",
    type: "debit",
  },
  {
    id: "11",
    date: "2024-01-05",
    description: "Movie Tickets",
    amount: -28.5,
    category: "Entertainment",
    type: "debit",
  },
  {
    id: "12",
    date: "2024-01-04",
    description: "Uber Ride",
    amount: -15.25,
    category: "Transportation",
    type: "debit",
  },
  {
    id: "13",
    date: "2024-01-03",
    description: "Bookstore",
    amount: -34.99,
    category: "Education",
    type: "debit",
  },
  {
    id: "14",
    date: "2024-01-02",
    description: "Gym Membership",
    amount: -49.99,
    category: "Health & Fitness",
    type: "debit",
  },
  {
    id: "15",
    date: "2024-01-01",
    description: "Interest Payment",
    amount: 12.45,
    category: "Income",
    type: "credit",
  },
  {
    id: "16",
    date: "2023-12-31",
    description: "Clothing Store",
    amount: -125.78,
    category: "Shopping",
    type: "debit",
  },
  {
    id: "17",
    date: "2023-12-30",
    description: "Water Bill",
    amount: -78.23,
    category: "Utilities",
    type: "debit",
  },
  {
    id: "18",
    date: "2023-12-29",
    description: "Pet Store",
    amount: -67.45,
    category: "Pets",
    type: "debit",
  },
  {
    id: "19",
    date: "2023-12-28",
    description: "Concert Tickets",
    amount: -95.0,
    category: "Entertainment",
    type: "debit",
  },
  {
    id: "20",
    date: "2023-12-27",
    description: "Car Repair",
    amount: -245.67,
    category: "Transportation",
    type: "debit",
  },
  {
    id: "21",
    date: "2023-12-26",
    description: "Gift Shop",
    amount: -56.32,
    category: "Shopping",
    type: "debit",
  },
  {
    id: "22",
    date: "2023-12-25",
    description: "Holiday Bonus",
    amount: 500,
    category: "Income",
    type: "credit",
  },
  {
    id: "23",
    date: "2023-12-24",
    description: "Pizza Delivery",
    amount: -18.75,
    category: "Food & Drink",
    type: "debit",
  },
  {
    id: "24",
    date: "2023-12-23",
    description: "Hardware Store",
    amount: -73.84,
    category: "Home Improvement",
    type: "debit",
  },
];
